### PR TITLE
support for java 11 and 17 at build time (#178)

### PR DESCRIPTION
**Pull request by mosidev**

### CODE REVIEW

**Comment by SoltauFintel** [comment]
Please do not use the star syntax.
import java.time.*;

**Comment by SoltauFintel** [comment]
I have this problem with Eclipse and Gradle:

Groovy:Unexpected problem with AST transform: The Spock compiler plugin cannot execute because Spock 2.1.0-groovy-3.0 is not compatible with Groovy 2.5.10. For more information (including enforce mode), see https://docs.spockframework.org (section 'Known Issues').
PoiCellDataTest.groovy
/jxls-poi/src/test/groovy/org/jxls/transform/poi

**Comment by mosidev** [comment]
> Please do not use the star syntax. import java.time.*;

This is the default behavior of the Intellij IDEA that converts more than 4 imports of same package into one with *

I will correct this and it would be great if you have some code conventions like this, mentioned them in the contribution guide.

**Comment by mosidev** [comment]
> I have this problem with Eclipse and Gradle:
> 
> Groovy:Unexpected problem with AST transform: The Spock compiler plugin cannot execute because Spock 2.1.0-groovy-3.0 is not compatible with Groovy 2.5.10. For more information (including enforce mode), see https://docs.spockframework.org (section 'Known Issues'). PoiCellDataTest.groovy /jxls-poi/src/test/groovy/org/jxls/transform/poi

Sorry i'm new in gradle and i didn't find groovy version requirement or other maven plugins that used in pom.xml in groovy build.gradle.
I also tried to build my changes with gradle but execution of gradle build leads to error on javadoc task.

can you help me on it?

**Comment by SoltauFintel** [comment]
With "-x javadoc" on the gradlew command line you can omit that task.

**Comment by mosidev** [comment]
I built my changes with gradle and that result was successful.
Is it ok?

```gradle
Executing 'build --rerun-tasks -x javadoc'...

> Task :jxls:compileJava
> Task :jxls:compileGroovy NO-SOURCE
> Task :jxls:processResources
> Task :jxls:classes
> Task :jxls:jar
> Task :jxls:javadocJar
> Task :jxls:sourcesJar
> Task :jxls:assemble

> Task :jxls:compileTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :jxls:compileTestGroovy
> Task :jxls:processTestResources
> Task :jxls:testClasses
> Task :jxls:test
> Task :jxls:check
> Task :jxls:build

> Task :jxls-poi:compileJava

> Task :jxls-poi:compileGroovy NO-SOURCE
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
> Task :jxls-poi:processResources NO-SOURCE
> Task :jxls-poi:classes
> Task :jxls-poi:jar
> Task :jxls-poi:javadocJar
> Task :jxls-poi:sourcesJar
> Task :jxls-poi:assemble
> Task :jxls-poi:compileTestJava
> Task :jxls-poi:compileTestGroovy
> Task :jxls-poi:processTestResources
> Task :jxls-poi:testClasses
> Task :jxls-poi:test
> Task :jxls-poi:check
> Task :jxls-poi:build

BUILD SUCCESSFUL in 51s
17 actionable tasks: 17 executed
```

**Comment by SoltauFintel** [comment]
I can't reproduce any Gradle javadoc / javadocJar error in your branch or master branch.

My Eclipse uses Groovy 2.4/2.5. I guess this is the cause. I need to take a closer look.

**Comment by SoltauFintel** [comment]
@mosidev Spock 2.1 has also a Groovy 2 release. Does a change to 'org.spockframework:spock-core:2.1-groovy-2.5' in jxls and jxls-poi work for you?

**Comment by mosidev** [comment]
I changed the spock-core version to 2.1-groovy-2.5 and worked with Java 8 and 11, but unfortunately did not work with Java 17:

```
Error occurred while calling a method on a Groovy class from classpath.: InvocationTargetException: BUG! exception in phase 'semantic analysis' in source unit 'jxls/src/test/groovy/org/jxls/area/XlsAreaGTest.groovy' Unsupported class file major version 61
```

**Comment by leonate** [comment]
Can you resolve the conflicts please?

**Review by leonate — APPROVED** [review]

**Comment by SoltauFintel** [comment]
I give my okay that this PR goes into the master and thus into the next release. ;-)

**Review by leonate — APPROVED** [review]

**Comment by SoltauFintel** [comment]
I've rebased this PR. See PR #212

**Comment by SoltauFintel** [comment]
@mosidev  2.13.0 has been released.

**Pull request closed without merging**
