### PR TITLE
Upgraded logback to 1.2.13

### PR DESCRIPTION
**Pull request by vgaur**
Upgraded logback in maven and gradle to handle critical CVE.

### CODE REVIEW

**Comment by SoltauFintel** [comment]
I think we should test if the newest version 1.4.14 works.

**Comment by SoltauFintel** [comment]
see #268

**Comment by SoltauFintel** [comment]
@vgaur What Java version do you use?

**Comment by vgaur** [comment]
@SoltauFintel  Currently I am using jdk 8 and in process of migrating to jdk17. I saw https://github.com/jxlsteam/jxls/issues/268 , Since these are critical I wanted to patch it right now and after this I can contribute on overall java 17 support.

**Review by SoltauFintel — APPROVED** [review]

**Pull request merged**
