### PR TITLE
Issue #235 POI 5.2.3

### PR DESCRIPTION
**Pull request by Sivakumar-finoli**
To Support latest version of Apache Poi - 5..2.3
    1. Modified POM dependencies of Apache POI to 5.2.3 from 4.1.2
    2. Removed dependency ooxml-schemas & added latest version of poi-ooxml
    3. Updated commons-compress version to 1.22 from 1.21
    4. Modified code to remove usage of deprecated functions - setCellType, cellTypeEnum & getFontIndexAsInt
    5. Ensured that all the test cases pass - Double Value in IssueB116Test had to be changed
    6. Changed project version to 2.13.0-SNAPSHOT
    7. Changed build.gradle file for version dependencies - but not tested gradle build

### CODE REVIEW

**Comment by SoltauFintel** [comment]
Thanks for your work.

I wonder why Github didn't start any actions.

**Comment by SoltauFintel** [comment]
closed as PR #247 continues

**Comment by Sivakumar-finoli** [comment]
Hi SoltauFintel,

Thanks for accepting the changes for POI version upgrade. When can we hope to see this change rolled out with your official release version?

Regards
Sivakumar

**Comment by SoltauFintel** [comment]
@Sivakumar-finoli  I guess this or next week. We're testing.

**Comment by SoltauFintel** [comment]
> @Sivakumar-finoli I guess this or next week. We're testing.

Because of bugs we can not release soon.

**Comment by Sivakumar-finoli** [comment]
Hi,

Is this related to the version change that I had pushed? If yes, please let me know specific scenarios or test cases where it is failing, and I can look into it over this weekend.

Siva

**Comment by SoltauFintel** [comment]
@Sivakumar-finoli 
It's a POI 5.2.3 bug. I can't tell/give you a testcase. We're still investigating. POI 5.2.2 is ok.

**Comment by Sivakumar-finoli** [comment]
Appreciate your feedback. Hope you will resolve the issue soon.

-- Siva

**Comment by SoltauFintel** [comment]
Cause is POI issue [65562](https://bz.apache.org/bugzilla/show_bug.cgi?id=65562). We're still investigating.

**Comment by SoltauFintel** [comment]
We advise against using POI 5.2.3. POI 5.2.2 can be used. An Apache POI bug ticket [66687](https://bz.apache.org/bugzilla/show_bug.cgi?id=66687) has been created.

**Comment by Sivakumar-finoli** [comment]
Thanks.. We have reverted to POI 5.2.2 based on your advice.  Waiting for you to release the tested version of JXLS with 5.2.2.

**Comment by SoltauFintel** [comment]
@Sivakumar-finoli  2.13.0 has been released.

**Pull request closed without merging**
