### PR TITLE
fix issue 51 test template

### LINKED ISSUE #51: Jxls template with dynamic columns and formula
Hey everyone, i'm using this library to generate a report and having some issues with a formula in a dynamic column;

My expected result:

expected

My current result:

result

This is my [template](https://github.com/jxlsteam/jxls/files/5190347/template.xlsx), [my current result](https://github.com/jxlsteam/jxls/files/5190365/result.xlsx) and  [my expected result](https://github.com/jxlsteam/jxls/files/5190369/expected.xlsx)

Anyone can help? Thank you

### PR DESCRIPTION
**Pull request by leonate**
Fix #51 by making the test green by modifying the template to have `jx:params(formulaStrategy="BY_COLUMN")` in the formula cell

### CODE REVIEW

**Comment by SoltauFintel** [comment]
There's already FormulaCopyDemo (with formula_copy_template.xls) that is showing the use of jx:params. I did not know that feature. We can delete this branch.

**Comment by SoltauFintel** [comment]
@leonate  squash or discard?

**Comment by leonate** [comment]
Right, I forgot, that we already have an example of that. Maybe we should that example to "Jx params demo" or something so that it is easier to find. We should also update the public documentation for that feature.

**Comment by SoltauFintel** [comment]
@leonate  You can do that or write an issue. ;-)

A different test case name would not have helped me because I did not even know the feature. Changing the documentation is of course good.

**Pull request closed without merging**
